import = ["~/.dotfiles/alacritty/themes/google.dark.toml"]

[cursor]
# - â–‡ Block
# - _ Underline
# - | Beam
style = "Block"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

[window]
opacity = 0.9
decorations = "Full"
